//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_18_20.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcademiaSistemasEntities : DbContext
    {
        public AcademiaSistemasEntities()
            : base("name=AcademiaSistemasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calificacione> Calificaciones { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<CursoCategoria> CursoCategorias { get; set; }
        public virtual DbSet<CursoHorario> CursoHorarios { get; set; }
        public virtual DbSet<CursoRecurso> CursoRecursoes { get; set; }
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<CursosMateria> CursosMaterias { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<Inscripcione> Inscripciones { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Nivele> Niveles { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<Profesore> Profesores { get; set; }
        public virtual DbSet<Recurso> Recursos { get; set; }
        public virtual DbSet<Requisito> Requisitos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
