//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_18_20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoCategoria
    {
        public int CursoCategoriaID { get; set; }
        public Nullable<int> CursoID { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
